name: Create website on github repo creation
on: workflow_dispatch
jobs:
  Create-Prismic-Repo-And-Push-Data-Models:
    runs-on: ubuntu-latest
    steps:
      - run: echo "üéâ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "üêß This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "üîé The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "üí° The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "üñ•Ô∏è The workflow is now ready to test your code on the runner."
      - name: Install packages
        run: npm install
      - name: Login through script
        env: # Set the secret as an input
          CMSRP_EMAIL: ${{ secrets.CMSRP_EMAIL }}
          CMSRP_PWD: ${{ secrets.CMSRP_PWD }}
        run: node --loader ts-node/esm utils/login.mts
      - name: Extract repo name from ${{ github.repository }}
        id: extract_repo
        run: |
          REPO_NAME="${{ github.repository }}"
          FORMATTED_REPO_NAME="${REPO_NAME#*/}"
          echo "Extracted repo name: $FORMATTED_REPO_NAME"
          echo "FORMATTED_REPO_NAME=$FORMATTED_REPO_NAME" >> $GITHUB_ENV
      - name: Run @slicemachine/init to push models
        run: npx @slicemachine/init@latest -r $FORMATTED_REPO_NAME
      - name: Install Vercel CLI
        run: npm install --global vercel
      # - name: Pull Vercel Environment Information
      #   run: vercel --scope prismic-solution-engineering pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy website on vercel
        env: # Set the secret as an input
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: vercel --scope prismic-solution-engineering --token=${{ secrets.VERCEL_TOKEN }} --prod --no-wait --build-env NEXT_PUBLIC_PRISMIC_ENVIRONMENT=$FORMATTED_REPO_NAME --env NEXT_PUBLIC_PRISMIC_ENVIRONMENT=$FORMATTED_REPO_NAME --yes

      # - name: Run initContent to push content
      #   env: # Set the secret as an input
      #     CMSRP_EMAIL: ${{ secrets.CMSRP_EMAIL }}
      #     CMSRP_PWD: ${{ secrets.CMSRP_PWD }}
      #     TARGET_REPO: ${{ env.FORMATTED_REPO_NAME }}
      #     CMSRP_API_KEY: ${{ secrets.CMSRP_API_KEY }}
      #   run: node --loader ts-node/esm utils/initContent.mts
          
      - run: echo "üçè This job's status is ${{ job.status }}."