name: Create website on github repo creation
on: create
jobs:
  Create-Prismic-Repo-And-Push-Data-Models:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "ğŸ–¥ï¸ The workflow is now ready to test your code on the runner."
      - name: Install packages
        run:
          npm install
      - name: Login through script
        with: # Set the secret as an input
          CMSRP_EMAIL: ${{ secrets.CMSRP_EMAIL }}
          CMSRP_PWD: ${{ secrets.CMSRP_PWD }}
        run:
          node --loader ts-node/esm utils/login.mts
      - name: Run @slicemachine/init to push models
        run:
          npx @slicemachine/init@latest -r website-factory-instance-alpha
          
      - run: echo "ğŸ This job's status is ${{ job.status }}."